language: java

jdk:
  - oraclejdk8

before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - nvm install 4.4

env:
  - BUILD_CMD="mvn -f catalog-spring-boot package"
  - BUILD_CMD="mvn -f gateway-vertx package"
  - BUILD_CMD="mvn -f inventory-wildfly-swarm package"
  - BUILD_CMD="npm install --prefix web-nodejs"
  - BUILD_CMD="mvn -f solutions/all/catalog-spring-boot package"
  - BUILD_CMD="mvn -f solutions/all/gateway-vertx package"
  - BUILD_CMD="mvn -f solutions/all/inventory-wildfly-swarm package"

script:
  - $BUILD_CMD