pipeline {
  agent {
      label 'maven'
  }
  stages {
    stage('Build JAR') { 
      steps {
        sh "cd inventory-thorntail && mvn package"
        sh "pwd"
        stash name:"jar", includes:"inventory-thorntail/target/inventory-1.0-SNAPSHOT-thorntail.jar"
      }
    }
    stage('Build Image') { 
      steps {
        sh "ls -la"
        unstash name:"jar"
        sh "ls -la"
        sh "ls -la inventory-thorntail"
        sh "ls -la inventory-thorntail/target"
        script {
          openshift.withCluster() {
            openshift.startBuild("inventory-s2i", "--from-file=inventory-thorntail/target/inventory-1.0-SNAPSHOT-thorntail.jar", "--wait")
          }
        }
      }
    }
    stage('Deploy') { 
      steps {
        sh "pwd"  
        script {
          openshift.withCluster() {
            def dc = openshift.selector("dc", "inventory")
            dc.rollout().latest()
            dc.rollout().status()
          }
        }
      }
    }
  }
}