pipeline {
  agent {
      label 'maven'
  }
  stages {
    stage('Build JAR') { 
      steps {
        sh "cd inventory-thorntail"  
        sh "mvn package"
        stash name:"jar", includes:"target/inventory-1.0-SNAPSHOT-thorntail.jar"
      }
    }
    stage('Build Image') { 
      steps {
        unstash name:"jar"
        script {
          openshift.withCluster() {
            openshift.startBuild("inventory-s2i", "--from-file=target/inventory-1.0-SNAPSHOT-thorntail.jar", "--wait")
          }
        }
      }
    }
    stage('Deploy') { 
      steps {
        script {
          openshift.withCluster() {
            def dc = openshift.selector("dc", "inventory")
            dc.rollout().latest()
            dc.rollout().status()
          }
        }
      }
    }
  }
}